---
- name: copy default jobs to machine
  sudo: yes
  copy: src={{ item }} dest={{ remote_tmp_folder }}/jobs owner={{ user_name  | default('vagrant') }} mode=600
  with_fileglob:
        - "{{ local_files_dir }}/jenkins/jobs/*.xml"
  register: default_jobs_copied

- name: copy java pipeline jobs to machine
  sudo: yes
  copy: src={{ item }} dest={{ remote_tmp_folder }}/jobs/java_pipeline owner={{ user_name  | default('vagrant') }} mode=600
  with_fileglob:
        - "{{ local_files_dir }}/jenkins/jobs/java_pipeline/*.xml"
  when: "target_jenkins_env == 'java'"
  register: java_pipeline_jobs_copied
