---
- name: copy default jobs to machine
  sudo: yes
  copy: src={{ item }} dest={{ remote_tmp_folder }}/jobs owner={{ user_name  | default('vagrant') }} mode=600
  with_fileglob:
        - "{{ local_files_dir }}/jenkins/jobs/*.xml"
  register: jobs_copied
