---
# Playbook that generates rsa_key pair for the Jenkins master machine.
# The rsa keys are used to transfer files over ssh to the tomcat webapps folder
# using the publish over ssh Jenkins plugin.

- name: Output user home directory
  sudo: yes
  command: ls /home/{{ user_name  | default('vagrant') }}
  when: target_jenkins_env == 'java' and install_tomcat
  register: user_home_dir_list

- name: Results - output from directory listing
  debug: var=user_home_dir_list.stdout_lines
  when: user_home_dir_list is defined

# Executes the shell command to generate the key files with the default settings (default file locations and no passphrase).
# This rsa_key is used for the java jenkins environment for deploying artifacts to tomcat
- name: generate rsa public and private key files
  sudo: yes
  shell: ssh-keygen -t rsa -N "" -f {{ rsa_key_file }}
  when: target_jenkins_env == 'java' and install_tomcat and user_home_dir_list.stdout.find('{{ rsa_key_file }}') == -1
  register: rsa_keygen_results

- name: Results - output from rsa keygen generation
  debug: var=rsa_keygen_results.stdout_lines
  when: rsa_keygen_results is defined
