---
# Playbook that generates rsa_key pair for the Jenkins master machine.
# The rsa keys are used to transfer files over ssh to the tomcat webapps folder
# using the publish over ssh Jenkins plugin.

# Executes the shell command to generate the key files at the file location specified (no passphrase).
# This rsa_key is used for the java jenkins environment for deploying artifacts to tomcat

- name: Output user ssh directory
  sudo: yes
  command: ls -la /home/{{ user_name  | default('vagrant') }}/{{ ssh_dir }}
  when: ssh_dir is defined
  register: user_ssh_dir_list

- name: Results - output user ssh directory
  debug: var=user_ssh_dir_list.stdout_lines
  when: user_ssh_dir_list is defined

- name: generate rsa public and private key files
  sudo: yes
  shell: ssh-keygen -t rsa -N "" -f {{ ssh_dir }}/{{ rsa_key_file }}
  when: rsa_key_file is defined and user_ssh_dir_list|success and user_ssh_dir_list.stdout.find('{{ rsa_key_file }}') == -1
  register: rsa_keygen_results

- name: Results - output from rsa keygen generation
  debug: var=rsa_keygen_results.stdout_lines
  when: rsa_keygen_results is defined
