# Configure Language Pack

- name: copy bash profile
  sudo: yes
  copy: src={{ local_files_dir }}/shell/.bash_profile dest={{ user_home  | default('/home/vagrant') }}/.bash_profile owner={{ user_name  | default('vagrant') }}
