---
#Create directories for groovy scripts and utility files
- name: make tmp directory to place script files
  sudo: yes
  shell: mkdir -p {{ remote_tmp_folder }}/script
  notify:
    - 'Delete Remote Temporary Folder'

# This will be a place to copy any files that your jenkins setup may need
# such as key files etc
- name: make shared folder between jenkins and ansible
  sudo: yes
  shell: mkdir -p {{ jenkins_home }}/shared_ansible

- include: copy-files.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
