---
# - name: Add nodejs ppa repository
#   sudo: yes
#   action: apt_repository repo='ppa:chris-lea/node.js' state=present

- name: Install nodejs-legacy
  sudo: yes
  action: "{{ ansible_pkg_mgr }} pkg=nodejs-legacy state=installed update-cache=yes"

- name: Install npm
  sudo: yes
  action: "{{ ansible_pkg_mgr }} pkg=npm state=installed update-cache=yes"
