---
startup_delay_s: 50
ansible_pkg_mgr: "apt"
jenkins_home: /var/lib/jenkins
vagrant_home: /home/vagrant

# for compat with the jenkins 'docker-pugin'.
# removing defaults to latest version of docker
docker_package: "lxc-docker-1.1.2"

mongo:
  install: false

# packages is a space delimited list eg. 'bower grunt-cli'
# bower, grunt-cli and istanbul are installed by default
npm:
  global_packages: ""
