---
# Set configurations for tools
- name: Set Git Global Name
  sudo: yes
  shell: 'git config --global user.name "{{ git.name }}"'
  when: git.name is defined

- name: Set Git Global Email
  sudo: yes
  shell: 'git config --global user.email "{{ git.email }}"'
  when: git.email is defined

- name: Set Git Default Push Method
  sudo: yes
  shell: git config --global push.default simple

- name: Install bower and grunt globally
  sudo: yes
  shell: sudo npm install -g bower grunt-cli
