---
# Hard-restart Jenkins
# Copy Job xml to be used in virtual machine
# Create jobs in jenkins instance
# run security script
- name: Restarting Jenkins NOW
  sudo: yes
  command: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 restart
  when: installed_plugins.changed
  register: hard_restart

- name: "{{ startup_delay_s | default(80) }}s delay while rebooting Jenkins"
  wait_for: port=8080 delay={{ startup_delay_s | default(80) }}
  when: hard_restart.changed

- name: list all jobs
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 list-jobs All
  register: existing_jobs

- name: create default jobs
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 create-job {{ item }} < /home/vagrant/tmp/jobs/{{ item }}.xml
  with_items: jenkins_jobs
  when: "existing_jobs.changed and jenkins_jobs is defined and existing_jobs.stdout.find('{{ item }}') == -1"
  register: jobs_created

- name: setup security
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 groovy /home/vagrant/tmp/script/security.groovy
  when: enable_security is defined and enable_security and jenkins_install.changed 
  register: security_setup
