---
# Copy Job xml to be used in virtual machine
# Create jobs in jenkins instance
- name: list all jobs
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 list-jobs All
  register: existing_jobs

- name: create default jobs
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 create-job {{ item }} < /home/vagrant/tmp/jobs/{{ item }}.xml
  with_items: jenkins_jobs
  when: "existing_jobs.changed and jenkins_jobs is defined and existing_jobs.stdout.find('{{ item }}') == -1"
  register: jobs_created

# - name: setup security
#   sudo: yes
#   shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 groovy /home/vagrant/tmp/script/security.groovy
#   #when: jenkins_install.changed
#   register: security_setup
