---
# Playbook to copy the publish over ssh plugin configs to jenkins
# and update it with the machine's rsa key and tomcat web apps folder
# The playbook begins by copying and updating the generated rsa key, if it exists.

- name: Copy rsa key to jenkins home
  sudo: yes
  command: cp /home/{{ user_name  | default('vagrant') }}/{{ rsa_key_file }} {{ jenkins_home }}
  when: rsa_keygen_results|success
  register: rsa_key_copied

- name: Update permissions for copied rsa_key
  sudo: yes
  command: chmod 400 {{ jenkins_home }}/{{ rsa_key_file }}
  when: rsa_key_copied|success
  register: rsa_key_chmod

- name: Change owner and group of copied rsa key to jenkins
  sudo: yes
  command: chown jenkins:jenkins {{ jenkins_home }}/{{ rsa_key_file }}
  when: rsa_key_chmod|success
  register: rsa_key_chown

- name: Copy publish over ssh config XML's to jenkins home
  sudo: yes
  copy: src={{ item }} dest={{ jenkins_home }} owner=jenkins mode=600
  with_fileglob:
        - "{{ local_files_dir_four_levels }}/jenkins/config/publish-over-ssh/{{ plugin_config_files.publish_over_ssh }}"
  when: tomcat_installed|success and rsa_key_chown|success and plugin_config_files is defined and plugin_config_files.publish_over_ssh is defined
  register: publish_over_SSH_configs_copied

- name: Set keyPath for publish over ssh config with rsa key file location
  sudo: yes
  replace: dest={{ jenkins_home }}/{{ plugin_config_files.publish_over_ssh }} regexp='{{ plugin_config_patterns.rsa_key_file }}' replace={{ jenkins_home }}/{{ rsa_key_file }}
  when: publish_over_SSH_configs_copied|success and plugin_config_patterns is defined and plugin_config_patterns.rsa_key_file is defined
  register: publish_over_SSH_configs_rsa_key_update

- name: Set remoteRootDir for publish over ssh config with tomcat web apps folder
  sudo: yes
  replace: dest={{ jenkins_home }}/{{ plugin_config_files.publish_over_ssh }} regexp='{{ plugin_config_patterns.tomcat_web_apps }}' replace={{ tomcat.web_apps_folder }}
  when: publish_over_SSH_configs_rsa_key_update|success and tomcat is defined and tomcat.web_apps_folder is defined and plugin_config_patterns.tomcat_web_apps is defined
