---
# Copy Job xml and plugins to be used in virtual machine
- name: make tmp directory to place job files
  sudo: yes
  shell: mkdir -p tmp/jobs
  notify:
    - 'Delete Remote Temporary Folder'

- name: make tmp directory to place plugin files
  sudo: yes
  shell: mkdir -p tmp/plugins
  notify:
    - 'Delete Remote Temporary Folder'

- name: make tmp directory to place script files
  sudo: yes
  shell: mkdir -p tmp/script
  notify:
    - 'Delete Remote Temporary Folder'

- name: copy scripts to machine
  sudo: yes
  copy: src={{ item }} dest={{ remote_tmp_folder }}/script owner=vagrant mode=600
  with_fileglob:
        - "{{ local_files_dir }}/jenkins/script/*.groovy"
  register: scripts_copied

- name: copy default jobs to machine
  sudo: yes
  copy: src={{ item }} dest={{ remote_tmp_folder }}/jobs owner=vagrant mode=600
  with_fileglob:
        - "{{ local_files_dir }}/jenkins/jobs/*.xml"
  register: jobs_copied

- name: copy plugins to machine
  sudo: yes
  copy: src={{ item }} dest={{ remote_tmp_folder }}/plugins owner=vagrant mode=600
  with_fileglob:
        - "{{ local_files_dir }}/jenkins/plugins/**/*.hpi"
  register: plugins_copied

- include: jenkins-configs.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
