---
# Copy Job xml and plugins to be used in virtual machine
- name: make tmp directory to place job files
  sudo: yes
  shell: mkdir -p tmp/jobs
  notify:
    - 'Delete Remote Temporary Folder'

- name: make tmp directory to place plugin files
  sudo: yes
  shell: mkdir -p tmp/plugins
  notify:
    - 'Delete Remote Temporary Folder'

- name: make tmp directory to place script files
  sudo: yes
  shell: mkdir -p tmp/script
  notify:
    - 'Delete Remote Temporary Folder'

# This will be a place to copy any files that your jenkins setup may need
# such as key files etc
- name: make shared folder between jenkins and ansible
  sudo: yes
  shell: mkdir -p {{ jenkins_home }}/shared_ansible

- include: copy-files.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
