---
# Requires python-setuptools
- name: Install pip
  sudo: yes
  command: "easy_install pip"

# Install pip packages
- name: Install listed pip packages
  sudo: yes
  command: "pip install {{ item }}"
  with_items: slave.pip.packages
  when: slave is defined and slave.pip is defined and slave.pip.packages is defined
