---
# Install redis
- name: Get redis deb key
  sudo: yes
  shell: 'wget -q http://d7jrzzvab3wte.cloudfront.net/checkbot/deb/redis-server_2.6.13-1_amd64.deb'
  when: install_redis

- name: unpack deb key
  sudo: yes
  shell: "sha1sum redis-server_2.6.13-1_amd64.deb | grep 'ab50cf037fd63e160946f8946b6d318cdf11800d'"
  when: install_redis

- name: install redis
  sudo: yes
  shell: 'dpkg -i redis-server_2.6.13-1_amd64.deb'
  when: install_redis

- name: Remove deb key after install
  sudo: yes
  shell: 'rm redis-server_2.6.13-1_amd64.deb'
  when: install_redis
